### ISSUE TITLE
Add option to compute ci for function field

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#10]
Figure1 shows plot_ci (plot credible interval) for KLExpantion type samples. Figure2 shows plot of the samples themselves. The discrepancy between how the ci looks and how the samples look is because for computing the ci, the ci is computed on the coefficient and then converted to function values (par2fun). We want to add an option for plot_ci to compute the ci for the function values rather than for the coefficients (Figure3).

![Image](https://user-images.githubusercontent.com/746326/185394244-bffc9270-5fe0-4202-ae87-cee75d4339f8.png)
Figure1
![Image](https://user-images.githubusercontent.com/746326/185394059-6f6a227b-b3b3-4f0d-aae1-74ec930e4c3b.png)
Figure2
![Image](https://user-images.githubusercontent.com/746326/185393885-6f9c6f12-0acb-444e-8c0e-f59037c382be.png)
Figure3

**Comment by nabriis** [comment]
I like this idea. We should consider if there are other use cases for computing statistics on the function values rather than parameters. For example, I could imagine it would be useful to compute the mean, std, ci etc. and plot the mean, std, and ci on both parameters and function values. 

In a way pretty much any statistics could be useful to do on either parameters or function values. Perhaps `Samples` should have a method to convert (or maybe create a new samples object) with the function values rather than samples.

**Comment by amal-ghamdi** [comment]
Thanks @nabriis for your comment. Agreed! for plotting ci for example, I needed also to covert the samples to function values before computing the mean. and this can apply to other statistics.

I am thinking of two approaches:

1. Add a flag in these methods: `to_func` for example. and possibly cash the funvals when computed.
2. Without adding a flag, just do something like: `funval_samples= samples.funvals` and apply methods on the new object `funval_samples`.

Let's bring this up in the stand-up today.
