### ISSUE TITLE
Discussion: Enable FD approximation for posterior gradient (density in general)

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#143]
Preliminary implementation in PR #142 

More to consider:

- [x]  Using FD approximation works with ULA and MALA, make sure it works for NUTS (especially when function space and parameter space dimensions are different) (issue added to address NUTS bug issue #157 )
- [x] Enable FD gradient for Density in general (can make parent method `gradient` in density that execute the FD logic if use_FD is enabled, then call subclass `_gradient` if use_FD is false )
- [x] Update the FD approximation method in utilities to accept CUQIarray
- [x] give user flexibility to specify FD method step size (also possibly user can pass the FD method itself. e.g. second order approximation) (Step can be controlled, but method not yet)
- [x] Decide if we want the accompanying demo to be in how-to or tutorial (It is a demo for now)

**Comment by amal-ghamdi** [comment]
@nabriis, I added the preliminary PR and more points here above to consider. I appreciate if you can take an initial look and let me know what do you think.

**Comment by nabriis** [comment]
As we talked about during stand-ups, I think we should consider adding this feature to the Density class level. It could be an optional keyword argument to the initializer, but should also be configurable after initialization.

I believe the reason It may not work for NUTS is because NUTS splits the Posterior into likelihood and prior internally (no real good reason for this, but I believe thats how it was implemented).
