### ISSUE TITLE
Improve ticks of samples.plot 

### ISSUE THREAD

**Issue by taniagoia11** [CUQI-DTU/CUQIpy#469]
**Description**

when plotting a Continous structure, the plot doesn't show any insight into the variation of the different variables 

**Example to reproduce**

The plot could have the dimensions on the y axis and the values on the x axis

**Comment by chaozg** [comment]
- I agree it doesn't make sense to show floats as x ticks since they are component indices. @taniagoia11 , is the second plot below something close to what you proposed? I forced the x tick to be integers there.
- As to x/y labels, I think it's better to leave them to the user and they can be easily set through `matplotlib`'s standard methods, like `plt.xlabel("x")`.

Before:
<img width="666" alt="Screenshot 2024-08-12 at 17 46 20" src="https://github.com/user-attachments/assets/366f5ca0-e641-40b3-ac3e-07d7d20a0972">
After:
<img width="664" alt="Screenshot 2024-08-12 at 17 47 26" src="https://github.com/user-attachments/assets/bf40c581-499c-4dd9-bd4e-65cdb8f05cb9">

**Comment by chaozg** [comment]
Just as @nabriis said, "there is not great solution without being explicit and setting geometry manually", we will keep the existing plot behaviour and leave it to the user. So this issue will be closed.
