### ISSUE TITLE
Rename existing solvers

### ISSUE THREAD

**Issue by chaozg** [CUQI-DTU/CUQIpy#599]
**General description of task**
- Class names of [solvers](https://github.com/CUQI-DTU/CUQIpy/blob/main/cuqi/solver/_solver.py) are not following a consistent convection, e.g., `minimize` and `LS`
- Unit tests for several solvers are missing

**Definition of Done (Feature/change)**
- [x] Rename relevant solvers
  - L_BFGS_B -> ScipyLBFGSB
  - minimize -> ScipyMinimizer
  - maximize -> ScipyMaximizer
  - LS -> ScipyLeastSquares
- [x] Any calls on relevant solvers are updated
- [x] Add unit tests for solvers

**Definition of Done (Mandatory)**
- [x] Documentation added (docstrings on all public methods/classes)
- [x] Unit tests added/updated (and passing!)
- [ ] Code reviewed and approved by 2 CUQI-maintainers
- [x] Online documentation is rendered correctly (esp. math) 

**Defintion of Done (Optional)**
- [ ] HowTo/tutorial added

**Comment by chaozg** [comment]
Hi @jakobsj, could you review the DoD here?

**Comment by jakobsj** [comment]
Thanks @chaozg I think everything makes sense, would like one addition namely to go through existing code base and make sure to update any calls to solvers to use the new names. May be covered by the "Rename" task but better to be explicit so that it is clear it has been done. If you agree, then with that DoD is approved.

**Comment by chaozg** [comment]
Thank @jakobsj . All calls to the relevant solvers have been updated and I just made it clear in the DoD.
